# Generated by Django 4.1.3 on 2022-11-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0002_account_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_side.apps'),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='categories',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_side.category'),
        ),
    ]
