# Generated by Django 4.1.3 on 2022-11-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0006_apps_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
