# Generated by Django 4.1.3 on 2022-11-30 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0007_apps_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarnedApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.apps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
