# Generated by Django 4.1.3 on 2022-11-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0008_earnedapps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
